apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: waveproject
  title: Onboarding Dev to project, repo, pipeline
  description: A workflow for a new engineer to begin building, testing, and coding.
  tags:
    - automation
    - self-service
    - harness
spec:
  owner: james.ha@harness.io
  type: service
  parameters:
    - title: Input Data
      properties:
        # This field is hidden but needed to authenticate the request to trigger the pipeline
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        username:
          title: username
          type: string 
          description: Enter the Harness User email to be onboarded to the project
          ui:autofocus: true
          
        Project:
          title: Choose a project to be onboarded to
          type: string
          enum: ['Wave Team', 'Tide Group', 'Tsunami Core']
          default: Wave Team
    - title: Project Team Details
      required:
        - owner 
      properties:
        owner:
          title: Choose an Group to join
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    # Call Harness Pipelines to create the service infra and other things
    - id: trigger
      name: Create all self-service components using harness templates
      action: trigger:harness-custom-pipeline
      input:
        url: 'https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/module/cd/orgs/demo/projects/Reference_Architecture/pipelines/Onboard_New_Dev/pipeline-studio/?storeType=INLINE&stageId=Provision_Harness_Resources&sectionId=EXECUTION'
        inputset:
          username: ${{ parameters.username }}
        apikey: ${{ parameters.token }}
